import type { Tool } from './types'

export const tools: Tool[] = [
  // === TEXT GENERATION (8) ===
  { id: '1', slug: 'chatgpt', name: 'ChatGPT', category: 'Text Generation', description: 'AI-powered conversational assistant.', pricing: 'Freemium', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg', website: 'https://chat.openai.com', rating: 4.9, tags: ['chatbot'] },
  { id: '2', slug: 'claude', name: 'Claude', category: 'Text Generation', description: 'Safe AI assistant from Anthropic.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnM91o7r1wba01xcHW15PLqbe-ONaTIjOO3g&s', website: 'https://claude.ai', rating: 4.8, tags: ['research'] },
  { id: '3', slug: 'gemini', name: 'Gemini', category: 'Text Generation', description: "Google's multimodal AI.", pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_oUB7fv4YZGhDdNb7_sut94PLQ1Hu3WwYJw&s', website: 'https://gemini.google.com', rating: 4.7, tags: ['google'] },
  { id: '4', slug: 'grok', name: 'Grok', category: 'Text Generation', description: "xAI's truth-seeking AI.", pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOv3K6RevHQCscoWPa2BvxKTq-9ygcQ4mhRA&s', website: 'https://grok.x.ai', rating: 4.6, tags: ['xai'] },
  { id: '5', slug: 'perplexity-ai', name: 'Perplexity AI', category: 'Text Generation', description: 'AI-powered answer engine.', pricing: 'Freemium', logo: 'https://images.seeklogo.com/logo-png/61/1/perplexity-ai-icon-black-logo-png_seeklogo-611679.png', website: 'https://www.perplexity.ai', rating: 4.9, tags: ['search'] },
  { id: '6', slug: 'poe', name: 'Poe', category: 'Text Generation', description: 'Multiple AI models in one place.', pricing: 'Freemium', logo: 'https://framerusercontent.com/assets/SMbX69lHmJHxofZELcvYbpHQ.png', website: 'https://poe.com', rating: 4.7, tags: ['multi-model'] },
  { id: '7', slug: 'you-com', name: 'You.com', category: 'Text Generation', description: 'AI search with chat.', pricing: 'Freemium', logo: 'https://upload.wikimedia.org/wikipedia/en/8/8f/Youcom_new_logo.jpg', website: 'https://you.com', rating: 4.6, tags: ['search'] },
  { id: '8', slug: 'character-ai', name: 'Character AI', category: 'Text Generation', description: 'Chat with AI characters.', pricing: 'Freemium', logo: 'https://character.ai/favicon.ico', website: 'https://character.ai', rating: 4.5, tags: ['characters'] },

  // === IMAGE GENERATION (10) ===
  { id: '9', slug: 'midjourney', name: 'Midjourney', category: 'Image Generation', description: 'AI art generator.', pricing: 'Paid', logo: 'https://images.ctfassets.net/lzny33ho1g45/1n2FSKrgaU9uiRimBWhnhP/200a8a01daa60b13f068f865e205ed54/Group_12467.jpg', website: 'https://www.midjourney.com', rating: 4.8, tags: ['art'] },
  { id: '10', slug: 'dalle3', name: 'DALL·E 3', category: 'Image Generation', description: 'OpenAI image generator.', pricing: 'Paid', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ97CJ1LrupmYhEN-Zwy1j5zrPjTXjR6puOiA&s', website: 'https://openai.com/dall-e-3', rating: 4.7, tags: ['images'] },
  { id: '11', slug: 'stable-diffusion', name: 'Stable Diffusion', category: 'Image Generation', description: 'Open-source image AI.', pricing: 'Free', logo: 'https://assets.topadvisor.com/media/_solution_logo_04032024_26265377.png', website: 'https://stability.ai', rating: 4.6, tags: ['open-source'] },
  { id: '12', slug: 'ideogram', name: 'Ideogram', category: 'Image Generation', description: 'AI with excellent text rendering.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDXnuji4Ot_L5Ev1sKgdopM2P0Gc3dHFoKiw&s', website: 'https://ideogram.ai', rating: 4.7, tags: ['text'] },
  { id: '13', slug: 'flux', name: 'Flux', category: 'Image Generation', description: 'High-quality open-source images.', pricing: 'Free', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMiAGKSFqZ6rbz8lzi0bfAc8dwM31d3xxN4IVm15mHRSQMy2HceTp6eNEXp8zSJADSMBk&usqp=CAU', website: 'https://blackforestlabs.ai', rating: 4.8, tags: ['high-quality'] },
  { id: '14', slug: 'leonardo-ai', name: 'Leonardo AI', category: 'Image Generation', description: 'AI for game assets.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW1H01VMToEJ_wVxpahpvAqT5aHjeI2XnK-w&s', website: 'https://leonardo.ai', rating: 4.6, tags: ['games'] },
  { id: '15', slug: 'firefly', name: 'Adobe Firefly', category: 'Image Generation', description: 'Adobe generative AI.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlMukayEXT5EEjPUGD5PHcK5nQlu-BMMG82w&s', website: 'https://firefly.adobe.com', rating: 4.5, tags: ['adobe'] },
  { id: '16', slug: 'playground-ai', name: 'Playground AI', category: 'Image Generation', description: 'Style customization AI.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqdauHfexk9FIlGbXVnx4d8KHtLIUArnGU3w&s', website: 'https://playgroundai.com', rating: 4.6, tags: ['styles'] },
  { id: '17', slug: 'replicate', name: 'Replicate', category: 'Image Generation', description: 'Run AI models with API.', pricing: 'Paid', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKtTS2PYsKNFAMFjtgnOs4qgOufi_XtUK8tg&s', website: 'https://replicate.com', rating: 4.7, tags: ['api'] },
  { id: '18', slug: 'civitai', name: 'Civitai', category: 'Image Generation', description: 'Stable Diffusion marketplace.', pricing: 'Free', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkPs8-ABvuQqaucFESyatb_eVim9oGTKpETA&s', website: 'https://civitai.com', rating: 4.8, tags: ['marketplace'] },

  // === CODING (8) ===
  { id: '19', slug: 'cursor', name: 'Cursor', category: 'Coding', description: 'AI code editor.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNk_Td9U-X3rbCCmwt4joXhsj7bBwpi3-U3w&s', website: 'https://cursor.sh', rating: 4.7, tags: ['IDE'] },
  { id: '20', slug: 'github-copilot', name: 'GitHub Copilot', category: 'Coding', description: 'AI pair programmer.', pricing: 'Paid', logo: 'https://img.icons8.com/fluent/1200/github-copilot.jpg', website: 'https://github.com/features/copilot', rating: 4.6, tags: ['coding'] },
  { id: '21', slug: 'codeium', name: 'Codeium', category: 'Coding', description: 'Free AI code completion.', pricing: 'Free', logo: 'https://codeium.gallerycdn.vsassets.io/extensions/codeium/codeium/1.49.2/1750056474392/Microsoft.VisualStudio.Services.Icons.Default', website: 'https://codeium.com', rating: 4.7, tags: ['free'] },
  { id: '22', slug: 'replit-ghostwriter', name: 'Replit Ghostwriter', category: 'Coding', description: 'AI for Replit.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHxDoTXMkYU19iZk_4os4y1QTYf5R7mgWM6Q&s', website: 'https://replit.com', rating: 4.5, tags: ['replit'] },
  { id: '23', slug: 'tabnine', name: 'Tabnine', category: 'Coding', description: 'Privacy-focused code completion.', pricing: 'Freemium', logo: 'https://cdn-public.softwarereviews.com/production/favicons/offerings/11681/original/6UeBPcDU_400x400__1_-removebg-preview.png', website: 'https://www.tabnine.com', rating: 4.6, tags: ['privacy'] },
  { id: '24', slug: 'v0', name: 'v0 by Vercel', category: 'Coding', description: 'AI React component generator.', pricing: 'Freemium', logo: 'https://images.ctfassets.net/lzny33ho1g45/l6hdgaIMZNqQpLUDDiw3e/86ecde28e347f93f4bdc78cfe8a0269e/v0-app-tips-hero.jpg?fm=jpg&q=31&fit=thumb&w=1520&h=760', website: 'https://v0.dev', rating: 4.8, tags: ['react'] },
  { id: '25', slug: 'windmill', name: 'Windmill', category: 'Coding', description: 'AI code generation for web apps.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGF9EJeM_Lg9hOuhLND-8iAOhVM2ka2_OJ1g&s', website: 'https://windmill.dev', rating: 4.5, tags: ['web'] },
  { id: '26', slug: 'sourcery', name: 'Sourcery', category: 'Coding', description: 'AI code reviewer.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ4xyOh17b1AQoQiG2jszDwsSPVoXjBYJoRQ&s', website: 'https://sourcery.ai', rating: 4.6, tags: ['review'] },

  // === VIDEO GENERATION (5) ===
  { id: '27', slug: 'runwayml', name: 'Runway', category: 'Video Generation', description: 'AI video editing.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3qi8ShndOjduTYHfKz6AUPdFI4y5hD9uY8w&s', website: 'https://runwayml.com', rating: 4.5, tags: ['video'] },
  { id: '28', slug: 'pika-labs', name: 'Pika Labs', category: 'Video Generation', description: 'Text-to-video AI.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzwDiNnKEAtGGOybPhMOyEcH-_bXbDjdQdKA&s', website: 'https://pika.art', rating: 4.6, tags: ['motion'] },
  { id: '29', slug: 'sora', name: 'Sora', category: 'Video Generation', description: 'OpenAI text-to-video.', pricing: 'Paid', logo: 'https://openai.com/favicon.ico', website: 'https://openai.com/sora', rating: 4.7, tags: ['openai'] },
  { id: '30', slug: 'luma-ai', name: 'Luma AI', category: 'Video Generation', description: 'Dream Machine video AI.', pricing: 'Freemium', logo: 'https://play-lh.googleusercontent.com/AQybb5Ro1vvBtYOWKxxdgrvalnLFIsx7dh50DDAQFpPtmrZ1A-5CKTTO2xAr_A-EZ_CX', website: 'https://lumalabs.ai', rating: 4.6, tags: ['dream'] },
  { id: '31', slug: 'kling-ai', name: 'Kling AI', category: 'Video Generation', description: 'High-quality video generation.', pricing: 'Freemium', logo: 'https://yt3.googleusercontent.com/SJReiD-oIxKhxlxjeaeSpOLLbeYct0en9nIIw15OHFdu17sVZ34PoclKbga7OQKk7TpSlBrbGA=s900-c-k-c0x00ffffff-no-rj', website: 'https://klingai.com', rating: 4.7, tags: ['high-quality'] },

  // === VOICE GENERATION (5) ===
  { id: '32', slug: 'elevenlabs', name: 'ElevenLabs', category: 'Voice Generation', description: 'Realistic AI voice generator.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNJgl2OHUmnQbovM0eVDUW_S0vk2K6uAUb6w&s', website: 'https://elevenlabs.io', rating: 4.8, tags: ['voice'] },
  { id: '33', slug: 'murf-ai', name: 'Murf AI', category: 'Voice Generation', description: 'Studio-quality text-to-speech.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJhv8LZVaWYyCRo9WNHIUgwElRU57EVnGINQ&s', website: 'https://murf.ai', rating: 4.7, tags: ['tts'] },
  { id: '34', slug: 'playht', name: 'PlayHT', category: 'Voice Generation', description: 'AI voiceovers.', pricing: 'Freemium', logo: 'https://framerusercontent.com/images/DETo14tTeDWoyjrja6BIohzXw.jpg', website: 'https://play.ht', rating: 4.6, tags: ['voiceover'] },
  { id: '35', slug: 'speechify', name: 'Speechify', category: 'Voice Generation', description: 'Text-to-speech with celebrity voices.', pricing: 'Freemium', logo: 'https://media.licdn.com/dms/image/v2/D4E0BAQFSRrH96Dmjyg/company-logo_200_200/company-logo_200_200/0/1706015775760/speechify_ai_studio_logo?e=2147483647&v=beta&t=kXRTKfLo1axGmf64Orp-uG_wzn4QcX0trNWc7jDV1ns', website: 'https://speechify.com', rating: 4.5, tags: ['celebrity'] },
  { id: '36', slug: 'respeecher', name: 'Respeecher', category: 'Voice Generation', description: 'AI voice cloning.', pricing: 'Paid', logo: 'https://www.respeecher.com/favicon.ico', website: 'https://www.respeecher.com', rating: 4.7, tags: ['cloning'] },

  // === SEARCH & RESEARCH (4) ===
  { id: '37', slug: 'tavily', name: 'Tavily', category: 'Search', description: 'AI-optimized search API.', pricing: 'Paid', logo: 'https://media.licdn.com/dms/image/v2/D4D0BAQEBo8xFnt9JVA/company-logo_200_200/company-logo_200_200/0/1727983378239/tavily_logo?e=2147483647&v=beta&t=g5QE2PczK2BZP5DcgKmIQGfEpoRoCKfKFgO7fHJnTxg', website: 'https://tavily.com', rating: 4.6, tags: ['api'] },
  { id: '38', slug: 'exa', name: 'Exa', category: 'Search', description: 'AI-powered web research.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-85K9AKu26OTRvSOQxFxgSkmNpRa88OGhbg&s', website: 'https://exa.ai', rating: 4.7, tags: ['research'] },
  { id: '39', slug: 'metaphor', name: 'Metaphor', category: 'Search', description: 'AI semantic search.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQU9ZIESR9H0Sgx8poMIpe8GEHRFIVAf-AjfA&s', website: 'https://metaphor.systems', rating: 4.6, tags: ['semantic'] },
  { id: '40', slug: 'searchgpt', name: 'SearchGPT', category: 'Search', description: 'OpenAI search prototype.', pricing: 'Paid', logo: 'https://openai.com/favicon.ico', website: 'https://openai.com/searchgpt', rating: 4.5, tags: ['openai'] },

  // === PRODUCTIVITY (5) ===
  { id: '41', slug: 'notion-ai', name: 'Notion AI', category: 'Productivity', description: 'AI for Notion notes.', pricing: 'Paid', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png', website: 'https://www.notion.so/product/ai', rating: 4.6, tags: ['notion'] },
  { id: '42', slug: 'mem', name: 'Mem', category: 'Productivity', description: 'AI-powered note-taking.', pricing: 'Freemium', logo: 'https://images.ctfassets.net/lzny33ho1g45/111ruxO33yVN94IVxL7SpA/6ab1ed8aa09250fa6f5861b2e20b39f1/mem-ai-00-hero.jpg?fm=jpg&q=31&fit=thumb&w=1520&h=760', website: 'https://getmem.com', rating: 4.5, tags: ['notes'] },
  { id: '43', slug: 'superhuman', name: 'Superhuman', category: 'Productivity', description: 'AI email client.', pricing: 'Paid', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgThbSh7p7PdU3ID87be_m_T8xEldoPoSuUw&s', website: 'https://superhuman.com', rating: 4.7, tags: ['email'] },
  { id: '44', slug: 'grammarly', name: 'Grammarly', category: 'Productivity', description: 'AI writing assistant.', pricing: 'Freemium', logo: 'https://play-lh.googleusercontent.com/6Xe9DWiMC76daosOC80Im9gqe25Q9P55LxJIGPTLbcdFkMXOur4mk8jTVxoqOaiAvAG4=w240-h480-rw', website: 'https://grammarly.com', rating: 4.6, tags: ['writing'] },
  { id: '45', slug: 'otter-ai', name: 'Otter.ai', category: 'Productivity', description: 'AI meeting transcription.', pricing: 'Freemium', logo: 'https://cdn.prod.website-files.com/63b9c43cf803b0331540fa68/67ef9e76a9bd9b3e47900153_otter.ai%20logo.png', website: 'https://otter.ai', rating: 4.7, tags: ['transcription'] },

  // === MUSIC GENERATION (3) ===
  { id: '46', slug: 'suno-ai', name: 'Suno AI', category: 'Music Generation', description: 'AI music from text.', pricing: 'Freemium', logo: 'https://play-lh.googleusercontent.com/5UR_1gDasYzAjJYSdx9onJ5FT68TVzxcV6O_FjTS2X_95_qHgexX__mCa_23lUIgWlU', website: 'https://suno.ai', rating: 4.8, tags: ['music'] },
  { id: '47', slug: 'udio', name: 'Udio', category: 'Music Generation', description: 'AI music creation.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0OLlS7EVS1iE-sos3Bnv6ousmJvlcxIsnAw&s', website: 'https://udio.com', rating: 4.7, tags: ['beats'] },
  { id: '48', slug: 'suno-v3', name: 'Suno V3', category: 'Music Generation', description: 'Latest Suno music AI.', pricing: 'Freemium', logo: 'https://play-lh.googleusercontent.com/5UR_1gDasYzAjJYSdx9onJ5FT68TVzxcV6O_FjTS2X_95_qHgexX__mCa_23lUIgWlU', website: 'https://suno.ai', rating: 4.9, tags: ['music'] },

  // === DESIGN & UI (4) ===
  { id: '49', slug: 'uizard', name: 'Uizard', category: 'Design', description: 'AI UI design from sketches.', pricing: 'Freemium', logo: 'https://pbs.twimg.com/profile_images/1593207623435927554/HSRG7VRu_400x400.jpg', website: 'https://uizard.io', rating: 4.6, tags: ['ui'] },
  { id: '50', slug: 'relume', name: 'Relume', category: 'Design', description: 'AI Webflow components.', pricing: 'Paid', logo: 'https://yt3.googleusercontent.com/MGRbvVhtCttJ7i2qW3igFxIJSkeoaRln_mIAFAfDgZIFD1yNUQC5mn1a5VqXKzcqRmAuDswu=s900-c-k-c0x00ffffff-no-rj', website: 'https://relume.io', rating: 4.7, tags: ['webflow'] },
  { id: '51', slug: 'framer-ai', name: 'Framer AI', category: 'Design', description: 'AI website generator.', pricing: 'Freemium', logo: 'https://res.cloudinary.com/apideck/image/upload/w_196,f_auto/v1557455842/catalog/framer/icon128x128.jpg', website: 'https://framer.com/ai', rating: 4.6, tags: ['websites'] },
  { id: '52', slug: 'autodraw', name: 'AutoDraw', category: 'Design', description: 'Google AI drawing tool.', pricing: 'Free', logo: 'https://www.autodraw.com/assets/images/autodraw-shareimage.png', website: 'https://www.autodraw.com', rating: 4.5, tags: ['drawing'] },


  { id: '53', slug: 'vizcom', name: 'Vizcom', category: 'Design', description: 'AI sketch to render.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYITmOaE7K3qEO09HK0IjWdAzpYjejZnjYzw&s', website: 'https://www.vizcom.ai', rating: 4.6, tags: ['sketch'] },
  { id: '54', slug: 'tldv', name: 'tldv', category: 'Productivity', description: 'AI meeting notes.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbo_wOScyHzdp7SU0uhRO1Q4OgO0PzL5SHBQ&s', website: 'https://tldv.io', rating: 4.7, tags: ['meetings'] },
  { id: '55', slug: 'arc-search', name: 'Arc Search', category: 'Search', description: 'AI browser search.', pricing: 'Free', logo: 'https://play-lh.googleusercontent.com/qYgB3jyi_AG1Iy7xnDgMBW8D6lg3YkVdJkkdSVccs7pGqsC8CcGF-S44yNs0-jp8dXGh', website: 'https://arc.net', rating: 4.8, tags: ['browser'] },
  { id: '56', slug: 'cleanvoice', name: 'Cleanvoice', category: 'Audio Editing', description: 'AI podcast cleaner.', pricing: 'Freemium', logo: 'https://pbs.twimg.com/profile_images/1778736691454394368/a5DPWdl-_400x400.jpg', website: 'https://cleanvoice.ai', rating: 4.6, tags: ['podcast'] },
  { id: '57', slug: 'qwen', name: 'Qwen', category: 'Text Generation', description: 'Alibaba AI model.', pricing: 'Free', logo: 'https://media.licdn.com/dms/image/v2/D560BAQFo8-ap8VHwUQ/company-logo_200_200/company-logo_200_200/0/1732514443393/qwen_logo?e=2147483647&v=beta&t=kGyrMtIcszl4ua7HjCah5Z7DwksqZvgn6kuozZyd-tY', website: 'https://qwen.ai', rating: 4.6, tags: ['chinese'] },
  { id: '58', slug: 'deepseek', name: 'DeepSeek', category: 'Coding', description: 'AI coding model.', pricing: 'Free', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfTMqGQZWeD9cV_X6m-a6lgRvz2SQFioOpuaaxqDI42HlSQXfGq0J-_4nQrw9f8ebbsJE&usqp=CAU', website: 'https://deepseek.com', rating: 4.7, tags: ['coding'] },
  { id: '59', slug: 'huggingchat', name: 'HuggingChat', category: 'Text Generation', description: 'Open-source chatbot.', pricing: 'Free', logo: 'https://huggingface.co/favicon.ico', website: 'https://huggingface.co/chat', rating: 4.6, tags: ['open-source'] },
  { id: '60', slug: 'blackbox-ai', name: 'Blackbox AI', category: 'Coding', description: 'AI code search.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLzOZn_fBjGrlN0eJPxDT_o_WNeAqsAA2NWQ&s', website: 'https://www.blackbox.ai', rating: 4.6, tags: ['code-search'] },
  { id: '61', slug: 'phind', name: 'Phind', category: 'Search', description: 'AI coding search.', pricing: 'Free', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvH5YsbQVHWFbXMoOiWTnTJRrYJb-Yug-2Hw&s', website: 'https://www.phind.com', rating: 4.7, tags: ['coding'] },
  { id: '62', slug: 'magicpattern', name: 'MagicPattern', category: 'Design', description: 'AI UI patterns.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvy8FrbK55k0vZaDD5a0zSRrYkE_JEe1rf6Q&s', website: 'https://magicpattern.ai', rating: 4.6, tags: ['ui'] },
  { id: '63', slug: 'stockimg-ai', name: 'Stockimg.ai', category: 'Image Generation', description: 'AI stock photos.', pricing: 'Freemium', logo: 'https://images.g2crowd.com/uploads/product/image/social_landscape/social_landscape_b363d11f12ff388c535c5c50cfd9623c/stockimg-ai.png', website: 'https://stockimg.ai', rating: 4.5, tags: ['stock'] },
  { id: '64', slug: 'neural-loves', name: 'Neural Loves', category: 'Image Generation', description: 'AI photo enhancer.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1wBMijAt9a1w4zXZc1FlVYs6p1jXTux0PSQ&s', website: 'https://neuralloves.com', rating: 4.6, tags: ['enhance'] },
  { id: '65', slug: 'adcreative-ai', name: 'AdCreative.ai', category: 'Marketing', description: 'AI ad creatives.', pricing: 'Paid', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKGXLdVkeAExPAQQgiKjNOk_dtf5Vq_H3OOg&s', website: 'https://adcreative.ai', rating: 4.7, tags: ['ads'] },
  { id: '66', slug: 'seo-writer', name: 'SEO Writer', category: 'Content Creation', description: 'AI SEO content.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7y3ayxwgeUeJgVz08HJee-Ypk-KOUgrQQOA&s', website: 'https://seowriting.ai/', rating: 4.5, tags: ['seo'] },
  { id: '67', slug: 'voila-ai-artist', name: 'Voilà AI Artist', category: 'Image Generation', description: 'AI art styles.', pricing: 'Freemium', logo: 'https://play-lh.googleusercontent.com/UH_EQMFB0ncCnNWhFikn2NKpU1bq8zD3yn8UQMKauxE9S5u74CdvB_NTT_Ch-dxR328', website: 'https://voilaaiartist.com', rating: 4.6, tags: ['art'] },
  { id: '68', slug: 'clipdrop', name: 'ClipDrop', category: 'Image Generation', description: 'AI image tools.', pricing: 'Freemium', logo: 'https://cdn.prod.website-files.com/6392f54210990d7ffbfca55f/64e4bce19276a23571153c45_Image-from-www.toools.design-on-2023-08-22-at-3.49.04-PM.svg', website: 'https://clipdrop.co', rating: 4.7, tags: ['images'] },
  { id: '69', slug: 'magify-design', name: 'Magify Design', category: 'Design', description: 'AI design tools.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe-vsKOtCn_DkG3oR5-n5leKEOqwSBRL8dSg&s', website: 'https://magify.design', rating: 4.5, tags: ['design'] },
  { id: '70', slug: 'kitbash3d', name: 'KitBash3D', category: '3D Generation', description: 'AI 3D models.', pricing: 'Paid', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6eHsmMdtVHXEQIs9I19K15xFiavve-qg1ag&s', website: 'https://kitbash3d.com', rating: 4.6, tags: ['3d'] },
  { id: '71', slug: 'meshy', name: 'Meshy', category: '3D Generation', description: 'Text-to-3D AI.', pricing: 'Freemium', logo: 'https://yt3.googleusercontent.com/J7y5ewent98lb0COTfsVbkcOZcBzPGzTsASuE7N-TzNVt0RjdvDSPF737gZft76ORTpieWMg=s900-c-k-c0x00ffffff-no-rj', website: 'https://www.meshy.ai', rating: 4.7, tags: ['3d'] },
  { id: '72', slug: 'kaedim', name: 'Kaedim', category: '3D Generation', description: '2D to 3D AI.', pricing: 'Paid', logo: 'https://pbs.twimg.com/profile_images/1615291187971104768/7s5gEY5F_400x400.jpg', website: 'https://www.kaedim3d.com', rating: 4.6, tags: ['3d'] },
  { id: '73', slug: 'luma-dream-machine', name: 'Luma Dream Machine', category: 'Video Generation', description: 'Advanced video AI.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHMDH4WbL17-at4mDIYizPA5PUO0GdJIWOGw&s', website: 'https://lumalabs.ai/dream-machine', rating: 4.8, tags: ['video'] },
  { id: '74', slug: 'pictory-ai', name: 'Pictory.ai', category: 'Video Generation', description: 'Script to video AI.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOetZ7YX1Y4UsFNxK715BOvsC4aCRvxt9rxQ&s', website: 'https://pictory.ai', rating: 4.6, tags: ['scripts'] },
  { id: '75', slug: 'synthesia-io', name: 'Synthesia.io', category: 'Video Generation', description: 'AI video avatars.', pricing: 'Paid', logo: 'https://asset.brandfetch.io/id0UsldsFb/id6_qCkQ7w.png', website: 'https://www.synthesia.io', rating: 4.8, tags: ['avatars'] },
  { id: '76', slug: 'runway-gen2', name: 'Runway Gen-2', category: 'Video Generation', description: 'Text-to-video AI.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8SfdkDPqEjK9hHySYrO3KzDaIvTxsTN6jfg&s', website: 'https://runwayml.com', rating: 4.7, tags: ['gen2'] },
  { id: '77', slug: 'phenaki', name: 'Phenaki', category: 'Video Generation', description: 'Google video AI.', pricing: 'Research', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgWLD0JE83JxjQhru6LZeu2qRG9Md4Pvu27g&s', website: 'https://sites.research.google/phenaki', rating: 4.6, tags: ['google'] },
  { id: '78', slug: 'make-a-video', name: 'Make-A-Video', category: 'Video Generation', description: 'Meta video AI.', pricing: 'Research', logo: 'https://images.seeklogo.com/logo-png/62/1/meta-ai-logo-png_seeklogo-624398.png', website: 'https://ai.facebook.com/blog/make-a-video', rating: 4.5, tags: ['meta'] },
  { id: '79', slug: 'imagen-video', name: 'Imagen Video', category: 'Video Generation', description: 'Google video AI.', pricing: 'Research', logo: 'https://i.ytimg.com/vi/yt0CE-bN--g/hqdefault.jpg', website: 'https://imagen.research.google/video', rating: 4.6, tags: ['google'] },
  { id: '80', slug: 'cogvideo', name: 'CogVideo', category: 'Video Generation', description: 'Zhipu AI video.', pricing: 'Research', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz3lq4YW3YBo4eQIeQmlNF0UVV_uY0WzFENQ&s', website: 'https://www.zhipuai.cn', rating: 4.5, tags: ['chinese'] },
   { id: '81', slug: 'chatsonic', name: 'ChatSonic', category: 'Text Generation', description: 'AI chatbot with voice integration.', pricing: 'Freemium', logo: 'https://images.ctfassets.net/lzny33ho1g45/7kka8yYaI1ip3BLlqV8AG5/329822f10f0430ac43ad720b3abb8c6d/chatsonic.jpg', website: 'https://writesonic.com/chatsonic', rating: 4.6, tags: ['voice', 'chatbot'] },
  { id: '82', slug: 'jasper-ai', name: 'Jasper AI', category: 'Content Creation', description: 'AI marketing copywriting.', pricing: 'Paid', logo: 'https://logo.clearbit.com/jasper.ai?size=512', website: 'https://www.jasper.ai', rating: 4.7, tags: ['marketing', 'copywriting'] },
  { id: '83', slug: 'synthesia', name: 'Synthesia', category: 'Video Generation', description: 'AI video avatars from text.', pricing: 'Paid', logo: 'https://asset.brandfetch.io/id0UsldsFb/id6_qCkQ7w.png', website: 'https://www.synthesia.io', rating: 4.8, tags: ['avatars', 'video'] },
  { id: '84', slug: 'copy-ai', name: 'Copy.ai', category: 'Content Creation', description: 'AI writing for ads & emails.', pricing: 'Freemium', logo: 'https://pbs.twimg.com/profile_images/1882909654545551360/QPAmppjU_400x400.jpg', website: 'https://www.copy.ai', rating: 4.6, tags: ['ads', 'emails'] },
  { id: '85', slug: 'deepl-write', name: 'DeepL Write', category: 'Content Creation', description: 'AI text enhancement tool.', pricing: 'Free', logo: 'https://pbs.twimg.com/profile_images/1676161802919374848/l2prRw3m_400x400.jpg', website: 'https://www.deepl.com/write', rating: 4.7, tags: ['writing', 'grammar'] },
  { id: '86', slug: 'pictory', name: 'Pictory', category: 'Video Generation', description: 'AI video from blog posts.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOetZ7YX1Y4UsFNxK715BOvsC4aCRvxt9rxQ&s', website: 'https://pictory.ai', rating: 4.5, tags: ['blog-to-video'] },
  { id: '87', slug: 'reface', name: 'Reface', category: 'Image Generation', description: 'AI face swap videos.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMNapBsOxNWTKLr3RmdPIDriNRsPxEp1AcXw&s', website: 'https://reface.ai', rating: 4.6, tags: ['faceswap'] },
  { id: '88', slug: 'lumen5', name: 'Lumen5', category: 'Video Generation', description: 'AI social video creator.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfe1BzLmUnDfhaNzQ484EZzoLpRTL6jSIWFQ&s', website: 'https://lumen5.com', rating: 4.5, tags: ['social', 'video'] },
  { id: '89', slug: 'beautiful-ai', name: 'Beautiful.ai', category: 'Design', description: 'AI presentation designer.', pricing: 'Freemium', logo: 'https://www.beautiful.ai/favicon.ico', website: 'https://www.beautiful.ai', rating: 4.6, tags: ['presentations'] },
  { id: '90', slug: 'writesonic', name: 'Writesonic', category: 'Content Creation', description: 'AI writing templates.', pricing: 'Freemium', logo: 'https://media.licdn.com/dms/image/v2/C4D0BAQGhlUgn8QU4Hg/company-logo_200_200/company-logo_200_200/0/1650618028463/writesonic_logo?e=2147483647&v=beta&t=pUQYY83b76uFQI2Rh4W8kQBlq-4SvjX_HnffU0QTlz8', website: 'https://writesonic.com', rating: 4.6, tags: ['templates'] },
  { id: '91', slug: 'deep-nostalgia', name: 'Deep Nostalgia', category: 'Image Generation', description: 'AI photo animation.', pricing: 'Free', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjmCp7DdZrMxMPqMcpNQdLzS0rh5RHVdgZyg&s', website: 'https://www.myheritage.com/deep-nostalgia', rating: 4.7, tags: ['photos'] },
  { id: '92', slug: 'synthesys', name: 'Synthesys', category: 'Voice Generation', description: 'AI human-like voices.', pricing: 'Paid', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpLRDWY9Oj424PpwW2qvYDiTZZ-X5UuWRV1ng3HmMQnH97pZcmIihXRQ0AosmdCgFygas&usqp=CAU', website: 'https://synthesys.io', rating: 4.6, tags: ['voiceovers'] },
  { id: '93', slug: 'ai-dungeon', name: 'AI Dungeon', category: 'Gaming', description: 'AI storytelling game.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFRxayTf4smZvSuwP-ZUfVzRrZUzAYAiPJJA&s', website: 'https://aidungeon.com', rating: 4.5, tags: ['games', 'stories'] },
  { id: '94', slug: 'timely', name: 'Timely', category: 'Productivity', description: 'AI calendar assistant.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGVmm_-QA54593t1jzXCpTkZQisteI5a9ROA&s', website: 'https://www.timely.com', rating: 4.6, tags: ['calendar'] },
  { id: '95', slug: 'inkforall', name: 'Ink For All', category: 'Content Creation', description: 'AI SEO writing.', pricing: 'Freemium', logo: 'https://cdn.prod.website-files.com/63994dae1033718bee6949ce/63c4966f7ceee985fff58218_inklogo2022.png', website: 'https://www.inkforall.com', rating: 4.5, tags: ['seo'] },
  { id: '96', slug: 'rytr', name: 'Rytr', category: 'Content Creation', description: 'AI writing assistant.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdsGsvOcjzROwt4z9ZGo-wk_qNYcQ9IvVRCw&s', website: 'https://rytr.me', rating: 4.6, tags: ['writing'] },
  { id: '97', slug: 'descript', name: 'Descript', category: 'Audio Editing', description: 'AI audio/video editor.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTCvLMJOFtYRZKdQvNSPpcCEjb6KT28Is9-g&s', website: 'https://www.descript.com', rating: 4.8, tags: ['audio', 'video'] },
  { id: '98', slug: 'remove-bg', name: 'Remove.bg', category: 'Image Generation', description: 'AI background remover.', pricing: 'Freemium', logo: 'https://www.remove.bg/favicon.ico', website: 'https://www.remove.bg', rating: 4.7, tags: ['background'] },
  { id: '99', slug: 'capsule', name: 'Capsule', category: 'Video Generation', description: 'AI video highlight creator.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-VDvG8JBQEjvKtyMZUtJaJUDK5ANxl7Rp7A&s', website: 'https://capsule.video', rating: 4.6, tags: ['highlights'] },
  { id: '100', slug: 'designs-ai', name: 'Designs.ai', category: 'Design', description: 'AI design generator.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEu4M0-q48UAkpnx5kbilaMoLfgHtFfMinBA&s', website: 'https://designs.ai', rating: 4.5, tags: ['design'] },
  { id: '101', slug: 'pep-talk', name: 'PepTalk', category: 'Voice Generation', description: 'AI motivational coach.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRO8KMgVYLpQbNzXP8U5-AVi5DxRYVTiOh1Dg&s', website: 'https://www.peptalk.ai', rating: 4.5, tags: ['coach'] },
  { id: '102', slug: 'kaiber', name: 'Kaiber', category: 'Video Generation', description: 'AI music video generator.', pricing: 'Freemium', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFaT0QLiYLhPzn8c2X7qohfgXkfkRT-gH5dQ&s', website: 'https://kaiber.ai', rating: 4.6, tags: ['music-video'] },
  { id: '103', slug: 'brandmark', name: 'Brandmark', category: 'Design', description: 'AI logo generator.', pricing: 'Paid', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrtIdOudUUPA_cp9Zc4QV4ojeDBESC5GdbFQ&s', website: 'https://brandmark.io', rating: 4.6, tags: ['logos'] },
  { id: '104', slug: 'headshotpro', name: 'HeadshotPro', category: 'Image Generation', description: 'AI professional headshots.', pricing: 'Paid', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFC4j_dYJdlt_64dLjJwTlC7M51uuYwjL6bQ&s', website: 'https://www.headshotpro.com', rating: 4.7, tags: ['headshots'] }


]

export function getAllTools(): Tool[] { return tools }
export function getToolBySlug(slug: string): Tool | undefined { return tools.find(tool => tool.slug === slug) }
export function getToolsByCategory(category: string): Tool[] { return tools.filter(tool => tool.category === category) }
export function searchTools(query: string): Tool[] {
  return tools.filter(tool =>
    tool.name.toLowerCase().includes(query.toLowerCase()) ||
    tool.description.toLowerCase().includes(query.toLowerCase()) ||
    tool.tags.some(tag => tag.toLowerCase().includes(query.toLowerCase()))
  )
}
